version: '3.2'

services:
  app:
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
    command: sh -c "yarn start:dev"
    networks:
      - docknet
    ports:
      - "5000:5000"


networks:
  docknet:
    external: true
